apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-deployer
  namespace: nuri-demo-project
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-deployer
  namespace: nuri-demo-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-deployer
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops